<?php

/**
 * CustomersToCustomerGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CustomersToCustomerGroups extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();
		
		$this->hasOne('Customers', array(
			'local' => 'customers_id',
			'foreign' => 'customers_id'
		));
		
		$this->hasOne('CustomerGroups', array(
			'local' => 'customer_groups_id',
			'foreign' => 'customer_groups_id'
		));
	}

	public function setUpParent(){
		$CustomersGroups = Doctrine::getTable('CustomerGroups')->getRecordInstance();
		$Customers = Doctrine::getTable('Customers')->getRecordInstance();
		
		$CustomersGroups->hasMany('CustomersToCustomerGroups', array(
			'local' => 'customer_groups_id',
			'foreign' => 'customer_groups_id',
			'cascade' => array('delete')
		));
		$Customers->hasMany('CustomersToCustomerGroups', array(
			'local' => 'customers_id',
			'foreign' => 'customers_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('customers_to_customer_groups');
		
		$this->hasColumn('customers_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
		
		$this->hasColumn('customer_groups_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
	}
}