<?php

/**
 * AdminGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class AdminGroups extends Doctrine_Record {
	
	public function setUp(){
		$this->setUpParent();
		
		$this->hasMany('Admin', array(
			'local' => 'admin_groups_id',
			'foreign' => 'admin_groups_id',
			'cascade' => array('delete')
		));
	}
	
	public function setUpParent(){
	}
	
	public function setTableDefinition(){
		$this->setTableName('admin_groups');
		
		$this->hasColumn('admin_groups_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => true
		));
		
		$this->hasColumn('admin_groups_name', 'string', 64, array(
			'type' => 'string',
			'length' => 64,
			'fixed' => false,
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false
		));
		
		$this->hasColumn('customer_login_allowed', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'default' => '0',
			'fixed' => false,
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false
		));
	}
}
?>