<?php

/**
 * Cache
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Cache extends Doctrine_Record {
	
	public function setTableDefinition(){
		$this->setTableName('cache');
		
		$this->hasColumn('cache_id', 'string', 32, array(
		'type' => 'string',
		'length' => 32,
		'fixed' => false,
		'primary' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_language_id', 'integer', 1, array(
		'type' => 'integer',
		'length' => 1,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_name', 'string', 255, array(
		'type' => 'string',
		'length' => 255,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_data', 'string', null, array(
		'type' => 'string',
		'fixed' => false,
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_global', 'integer', 1, array(
		'type' => 'integer',
		'length' => 1,
		'unsigned' => 0,
		'primary' => false,
		'default' => '1',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_gzip', 'integer', 1, array(
		'type' => 'integer',
		'length' => 1,
		'unsigned' => 0,
		'primary' => false,
		'default' => '1',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_method', 'string', 20, array(
		'type' => 'string',
		'length' => 20,
		'fixed' => false,
		'primary' => false,
		'default' => 'RETURN',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_date', 'timestamp', null, array(
		'type' => 'timestamp',
		'primary' => false,
		'default' => '0000-00-00 00:00:00',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('cache_expires', 'timestamp', null, array(
		'type' => 'timestamp',
		'primary' => false,
		'default' => '0000-00-00 00:00:00',
		'notnull' => true,
		'autoincrement' => false,
		));
	}
}