<?php

/**
 * CompareReports
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CompareReports extends Doctrine_Record {
	
	public function setUp(){
		$this->hasMany('CompareReportsDiffs', array(
			'local'   => 'report_id',
			'foreign' => 'report_id',
			'cascade' => array('delete')
		));
	}
	
	public function preInsert($event){
		$this->date_added = date('Y-m-d h:i:s');
	}
	
	public function setTableDefinition(){
		$this->setTableName('compare_reports');
		
		$this->hasColumn('report_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));
		
		$this->hasColumn('date_added', 'timestamp', null, array(
			'type'          => 'timestamp',
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));
		
		$this->hasColumn('left_side', 'string', 128, array(
			'type'          => 'string',
			'length'        => 128,
			'default'       => '',
			'notnull'       => true
		));
		
		$this->hasColumn('right_side', 'string', 128, array(
			'type'          => 'string',
			'length'        => 128,
			'default'       => '',
			'notnull'       => true
		));
	}
}