<?php

/**
 * CompareReportsDiffs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CompareReportsDiffs extends Doctrine_Record {
	
	public function setUp(){
	}
	
	public function setTableDefinition(){
		$this->setTableName('compare_reports_diffs');
		
		$this->hasColumn('diff_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));
		
		$this->hasColumn('report_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => false
		));
		
		$this->hasColumn('message', 'string', 999, array(
			'type'          => 'string',
			'length'        => 999,
			'default'       => '',
			'notnull'       => true
		));
		
		$this->hasColumn('left_file', 'string', 999, array(
			'type'          => 'string',
			'length'        => 999,
			'default'       => '',
			'notnull'       => true
		));
		
		$this->hasColumn('right_file', 'string', 999, array(
			'type'          => 'string',
			'length'        => 999,
			'default'       => '',
			'notnull'       => true
		));
	}
}