<?php

/**
 * CounterHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CounterHistory extends Doctrine_Record {
	
	public function setTableDefinition(){
		$this->setTableName('counter_history');
		
		$this->hasColumn('month', 'string', 8, array(
		'type' => 'string',
		'length' => 8,
		'fixed' => true,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('counter', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
	}
}