<?php

/**
 * Countries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Countries extends Doctrine_Record {
	
	public function setUp(){
		$this->hasOne('AddressFormat', array(
			'local'   => 'address_format_id',
			'foreign' => 'address_format_id'
		));
		
		$this->hasMany('Zones', array(
			'local'   => 'countries_id',
			'foreign' => 'zone_country_id',
			'cascade' => array('delete')
		));
	}
	
	public function setTableDefinition(){
		$this->setTableName('countries');
		
		$this->hasColumn('countries_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('countries_name', 'string', 64, array(
		'type' => 'string',
		'length' => 64,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('countries_iso_code_2', 'string', 2, array(
		'type' => 'string',
		'length' => 2,
		'fixed' => true,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('countries_iso_code_3', 'string', 3, array(
		'type' => 'string',
		'length' => 3,
		'fixed' => true,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('address_format_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
	}
}