<?php

/**
 * CustomersInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CustomersInfo extends Doctrine_Record {
	
	public function preInsert($event){
		$this->customers_info_date_account_created = date('Y-m-d H:i:s');
	}
	
	public function preUpdate($event){
		$this->customers_info_date_account_last_modified = date('Y-m-d H:i:s');
	}
	
	public function setTableDefinition(){
		$this->setTableName('customers_info');
		
		$this->hasColumn('customers_info_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
		
		$this->hasColumn('customers_info_date_of_last_logon', 'timestamp', null, array(
			'type' => 'timestamp',
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
		
		$this->hasColumn('customers_info_number_of_logons', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
		
		$this->hasColumn('customers_info_date_account_created', 'timestamp', null, array(
			'type' => 'timestamp',
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
		
		$this->hasColumn('customers_info_date_account_last_modified', 'timestamp', null, array(
			'type' => 'timestamp',
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
		
		$this->hasColumn('global_product_notifications', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => false,
			'default' => '0',
			'notnull' => false,
			'autoincrement' => false,
		));
	}
}