<?php

/**
 * EmailTemplates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class EmailTemplates extends Doctrine_Record {

	public function setUp(){
		$this->hasMany('EmailTemplatesDescription', array(
			'foreign' => 'email_templates_id',
			'local' => 'email_templates_id',
			'cascade' => array('delete')
		));
		
		$this->hasMany('EmailTemplatesVariables', array(
			'foreign' => 'email_templates_id',
			'local' => 'email_templates_id',
			'cascade' => array('delete')
		));
	}
	public function setTableDefinition(){
		$this->setTableName('email_templates');
		
		$this->hasColumn('email_templates_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('email_templates_name', 'string', 32, array(
		'type' => 'string',
		'length' => 32,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('email_templates_event', 'string', 32, array(
		'type' => 'string',
		'length' => 32,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('email_templates_attach', 'string', 255, array(
		'type' => 'string',
		'length' => 255,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('is_disabled', 'integer', 1, array(
				'type' => 'integer',
				'length' => 1,
				'unsigned' => 0,
				'primary' => false,
				'default' => '0',
				'notnull' => true,
				'autoincrement' => false,
		));
	}
}