<?php

/**
 * FunwaysProductsToCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class FunwaysProductsToCategories extends Doctrine_Record {
	
	public function setUp(){
		$this->setUpParent();
	}
	
	public function setUpParent(){
		$FunwaysProducts = Doctrine_Core::getTable('FunwaysProducts')->getRecordInstance();
		$FunwaysCategories = Doctrine_Core::getTable('FunwaysCategories')->getRecordInstance();
		
		$FunwaysProducts->hasMany('FunwaysProductsToCategories', array(
			'local' => 'products_id',
			'foreign' => 'products_id',
			'cascade' => array('delete')
		));
		
		$FunwaysCategories->hasMany('FunwaysProductsToCategories', array(
			'local' => 'categories_id',
			'foreign' => 'categories_id',
			'cascade' => array('delete')
		));
	}
	
	public function setTableDefinition(){
		$this->setTableName('funways_products_to_categories');
		$this->hasColumn('products_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('categories_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => false,
		));
	}
}