<?php

/**
 * Manufacturers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Manufacturers extends Doctrine_Record {
	
	public function setUp(){
		$this->setUpParent();
		
		$this->hasMany('ManufacturersInfo', array(
			'local' => 'manufacturers_id',
			'foreign' => 'manufacturers_id',
			'cascade' => array('delete')
		));
		
		$this->hasMany('Products', array(
			'local' => 'manufacturers_id',
			'foreign' => 'manufacturers_id'
		));
	}
	
	public function setUpParent(){
	}
	
	public function preInsert($event){
		$this->date_added = date('Y-m-d H:i:s');
	}
	
	public function preUpdate($event){
		$this->last_modified = date('Y-m-d H:i:s');
	}
	
	public function setTableDefinition(){
		$this->setTableName('manufacturers');
		
		$this->hasColumn('manufacturers_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => true,
		));
		
		$this->hasColumn('manufacturers_name', 'string', 32, array(
			'type' => 'string',
			'length' => 32,
			'fixed' => false,
			'primary' => false,
			'default' => '',
			'notnull' => true,
			'autoincrement' => false,
		));
		
		$this->hasColumn('manufacturers_image', 'string', 64, array(
			'type' => 'string',
			'length' => 64,
			'fixed' => false,
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
		
		$this->hasColumn('date_added', 'timestamp', null, array(
			'type' => 'timestamp',
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
		
		$this->hasColumn('last_modified', 'timestamp', null, array(
			'type' => 'timestamp',
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
	}
}