<?php

/**
 * MonerisCanOrders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class MonerisCanOrders extends Doctrine_Record {
	
	public function setTableDefinition(){
		$this->setTableName('moneris_can_orders');
		
		$this->hasColumn('moneris_order_id', 'string', 50, array(
		'type' => 'string',
		'length' => 50,
		'fixed' => false,
		'primary' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('gateway_url', 'string', 30, array(
		'type' => 'string',
		'length' => 30,
		'fixed' => false,
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('osc_order_id', 'string', 11, array(
		'type' => 'string',
		'length' => 11,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('osc_session', 'string', 32, array(
		'type' => 'string',
		'length' => 32,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('f4l4', 'string', 16, array(
		'type' => 'string',
		'length' => 16,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('ref_num', 'string', 18, array(
		'type' => 'string',
		'length' => 18,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('resp_code', 'string', 5, array(
		'type' => 'string',
		'length' => 5,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('iso_code', 'string', 5, array(
		'type' => 'string',
		'length' => 5,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('auth_code', 'string', 8, array(
		'type' => 'string',
		'length' => 8,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('trans_date', 'string', 12, array(
		'type' => 'string',
		'length' => 12,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('trans_time', 'string', 10, array(
		'type' => 'string',
		'length' => 10,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('trans_type', 'string', 10, array(
		'type' => 'string',
		'length' => 10,
		'fixed' => false,
		'primary' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('message', 'string', 100, array(
		'type' => 'string',
		'length' => 100,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('card_type', 'string', 10, array(
		'type' => 'string',
		'length' => 10,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('txn_num', 'string', 20, array(
		'type' => 'string',
		'length' => 20,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('avs_code', 'string', 5, array(
		'type' => 'string',
		'length' => 5,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('cvd_code', 'string', 5, array(
		'type' => 'string',
		'length' => 5,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('crypt_type', 'string', 5, array(
		'type' => 'string',
		'length' => 5,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('veres', 'string', 50, array(
		'type' => 'string',
		'length' => 50,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('pares', 'string', 50, array(
		'type' => 'string',
		'length' => 50,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
	}
}