<?php

/**
 * OrdersStatusHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class OrdersStatusHistory extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();
		$this->hasOne('Orders', array(
			'local' => 'orders_id',
			'foreign' => 'orders_id'
		));
		
		$this->hasOne('OrdersStatus', array(
			'local' => 'orders_status_id',
			'foreign' => 'orders_status_id'
		));
	}
	
	public function preInsert($event){
		$this->date_added = date('Y-m-d H:i:s');
	}
	
	public function preUpdate($event){
	}

	public function setUpParent(){
	}

	public function setTableDefinition(){
		$this->setTableName('orders_status_history');
		
		$this->hasColumn('orders_status_history_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('orders_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('orders_status_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('date_added', 'timestamp', null, array(
		'type' => 'timestamp',
		'primary' => false,
		'default' => '0000-00-00 00:00:00',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('customer_notified', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('comments', 'string', null, array(
		'type' => 'string',
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
	}
}