<?php

/**
 * OrdersStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class OrdersStatus extends Doctrine_Record {

	public function setUp(){
		parent::setUp();
		
		$this->hasMany('OrdersStatusDescription', array(
			'local' => 'orders_status_id',
			'foreign' => 'orders_status_id',
			'cascade' => array('delete')
		));
	}
	
	public function setTableDefinition(){
		$this->setTableName('orders_status');
		
		$this->hasColumn('orders_status_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
	}
}