<?php

/**
 * Orders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ProductsListing extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();
		
		$this->hasMany('ProductsListingDescription', array(
			'local' => 'products_listing_id',
			'foreign' => 'products_listing_id',
			'cascade' => array('delete')
		));
	}
	
	public function setUpParent(){
	}

	public function setTableDefinition(){
		$this->setTableName('products_listing');

		$this->hasColumn('products_listing_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('products_listing_status', 'integer', 1, array(
		'type' => 'integer',
		'length' => 1,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_sort_order', 'integer', 3, array(
		'type' => 'integer',
		'length' => 3,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_allow_sort', 'integer', 1, array(
		'type' => 'integer',
		'length' => 1,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_default_sorting', 'integer', 1, array(
		'type' => 'integer',
		'length' => 1,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_sort_key', 'string', 64, array(
		'type' => 'string',
		'length' => 64,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_sort_column', 'string', 255, array(
		'type' => 'string',
		'length' => 255,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_heading_align', 'string', 12, array(
		'type' => 'string',
		'length' => 12,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_heading_valign', 'string', 12, array(
		'type' => 'string',
		'length' => 12,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_module', 'string', 64, array(
		'type' => 'string',
		'length' => 64,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('products_listing_template', 'string', 1000, array(
		'type' => 'string',
		'length' => 1000,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => false,
		'autoincrement' => false,
		));
	}
}