<?php

/**
 * ProgressBar
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ProgressBar extends Doctrine_Record {

	public function setTableDefinition(){
		$this->setTableName('progress_bar');

		$this->hasColumn('id', 'integer', 11, array(
			'type' => 'integer',
			'length' => 11,
			'unsigned' => 0,
			'primary' => true,
			'notnull' => true,
			'autoincrement' => true,
		));
		$this->hasColumn('name', 'string', 32, array(
			'type' => 'string',
			'length' => 32,
			'fixed' => false,
			'primary' => false,
			'notnull' => true
		));
		$this->hasColumn('message', 'string', 999, array(
			'type' => 'string',
			'fixed' => false,
			'primary' => false,
			'notnull' => true
		));
		$this->hasColumn('percentage', 'integer', 2, array(
			'type' => 'integer',
			'length' => 2,
			'unsigned' => 0,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));
	}
}