<?php

/**
 * RentalTop
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class RentalTop extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();
	}

	public function preInsert($event){
		$this->date_modified = date('Y-m-d H:i:s');
	}

	public function preUpdate($event){
		$this->date_modified = date('Y-m-d H:i:s');
	}

	public function setUpParent(){
		$Products = Doctrine_Core::getTable('Products')->getRecordInstance();

		$Products->hasMany('RentalTop', array(
			'local' => 'products_id',
			'foreign' => 'products_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('rental_top');

		$this->hasColumn('rental_top_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('products_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('top', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('date_modified', 'timestamp', null, array(
		'type'          => 'timestamp',
		'primary'       => false,
		'notnull'       => false,
		'autoincrement' => false
		));

	}
}