<?php

/**
 * RentalAvailability
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class RentalAvailability extends Doctrine_Record {
	public function setUp(){
		$this->hasMany('RentalAvailabilityDescription', array(
			'local' => 'rental_availability_id',
			'foreign' => 'rental_availability_id',
			'cascade' => array('delete')
		));
	}
	public function setTableDefinition(){
		$this->setTableName('rental_availability');
		
		$this->hasColumn('rental_availability_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('ratio', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
	}
}