<?php

/**
 * SearchwordSwap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class SearchwordSwap extends Doctrine_Record {

	public function setTableDefinition(){
		$this->setTableName('searchword_swap');

		$this->hasColumn('sws_id', 'integer', 3, array(
		'type' => 'integer',
		'length' => 3,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('sws_word', 'string', 100, array(
		'type' => 'string',
		'length' => 100,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('sws_replacement', 'string', 100, array(
		'type' => 'string',
		'length' => 100,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
	}
}