<?php

/**
 * Sessions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Sessions extends Doctrine_Record {
	
	public function setTableDefinition(){
		$this->setTableName('sessions');
		$this->hasColumn('sesskey', 'string', 32, array(
		'type' => 'string',
		'length' => 32,
		'fixed' => false,
		'primary' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('expiry', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 1,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('value', 'string', null, array(
		'type' => 'string',
		'fixed' => false,
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
	}
}