<?php

/**
 * SesUpdates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class SesUpdates extends Doctrine_Record {
	
	public function setUp(){
	}
	
	public function setTableDefinition(){
		$this->setTableName('ses_updates');
		
		$this->hasColumn('update_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => true
		));
		
		$this->hasColumn('update_number', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'primary' => false,
			'notnull' => true
		));
		
		$this->hasColumn('update_name', 'string', 128, array(
			'type' => 'string',
			'length' => 128,
			'primary' => false,
			'default' => '',
			'notnull' => true
		));
		
		$this->hasColumn('update_description', 'string', 999, array(
			'type' => 'string',
			'primary' => false,
			'notnull' => false
		));
		
		$this->hasColumn('update_date', 'date', null, array(
			'type' => 'date',
			'primary' => false,
			'notnull' => false
		));
		
		/*
		 * 0 = Not Installed
		 * 1 = Installed
		 * 2 = Hidden
		 */
		$this->hasColumn('update_status', 'integer', 2, array(
			'type' => 'integer',
			'length' => 2,
			'default' => '0',
			'autoincrement' => false
		));
		
		$this->hasColumn('update_latest_commit', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'default' => '0',
			'autoincrement' => false
		));
	}
}