<?php

/**
 * Products
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Suppliers extends Doctrine_Record {

	public function setUp(){
		parent::setUp();
		
		$this->hasMany('ProductsInventoryBarcodes', array(
			'local' => 'suppliers_id',
			'foreign' => 'suppliers_id',
			'cascade' => array('delete')
		));		
		
	}
	
	public function preInsert($event){
		$this->suppliers_date_added = date('Y-m-d H:i:s');
	}
	
	public function preUpdate($event){
		$this->suppliers_last_modified = date('Y-m-d H:i:s');
	}
	
	public function setTableDefinition(){
		$this->setTableName('suppliers');

		$this->hasColumn('suppliers_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));
		
		$this->hasColumn('acquisition_cost', 'decimal', 15, array(
			'type'          => 'decimal',
			'length'        => 15,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0.0000',
			'notnull'       => true,
			'autoincrement' => false,
			'scale'         => 4
		));
		
	}
	
}
?>