<?php

/**
 * Products
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Suppliers extends Doctrine_Record {

	public function setUp(){
		parent::setUp();
		
		$this->hasMany('ProductsInventoryBarcodes', array(
			'local' => 'suppliers_id',
			'foreign' => 'suppliers_id',
			'cascade' => array('delete')
		));		
		
	}
	
	public function preInsert($event){
		$this->suppliers_date_added = date('Y-m-d H:i:s');
	}
	
	public function preUpdate($event){
		$this->suppliers_last_modified = date('Y-m-d H:i:s');
	}
	
	public function setTableDefinition(){
		$this->setTableName('suppliers');

		$this->hasColumn('suppliers_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));

        $this->hasColumn('suppliers_name', 'string', 50, array(
            'type' => 'string',
            'length' => 50,
            'fixed' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false
        ));

        $this->hasColumn('suppliers_address', 'string', 250, array(
            'type' => 'string',
            'length' => 250,
            'fixed' => false,
            'primary' => false,
            'default' => '',
            'notnull' => false,
            'autoincrement' => false
        ));

        $this->hasColumn('suppliers_phone', 'string', 20, array(
            'type' => 'string',
            'length' => 20,
            'fixed' => false,
            'primary' => false,
            'default' => '',
            'notnull' => false,
            'autoincrement' => false
        ));

        $this->hasColumn('suppliers_website', 'string', 250, array(
            'type' => 'string',
            'length' => 250,
            'fixed' => false,
            'primary' => false,
            'default' => '',
            'notnull' => false,
            'autoincrement' => false
        ));

        $this->hasColumn('suppliers_notes', 'string', 250, array(
            'type' => 'string',
            'length' => 250,
            'fixed' => false,
            'primary' => false,
            'default' => '',
            'notnull' => false,
            'autoincrement' => false
        ));

        $this->hasColumn('suppliers_date_added', 'timestamp', null, array(
            'type'          => 'timestamp',
            'primary'       => false,
            'default'       => '0000-00-00 00:00:00',
            'notnull'       => true,
            'autoincrement' => false
        ));
        $this->hasColumn('suppliers_last_modified', 'timestamp', null, array(
            'type'          => 'timestamp',
            'primary'       => false,
            'notnull'       => false,
            'autoincrement' => false
        ));
		
	}
	
}
?>