<?php

/**
 * TaxRates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class TaxRates extends Doctrine_Record {
	
	public function setUp(){
		$this->hasOne('TaxClass', array(
			'local' => 'tax_class_id',
			'foreign' => 'tax_class_id'
		));
		
		$this->hasOne('GeoZones', array(
			'local' => 'tax_zone_id',
			'foreign' => 'geo_zone_id'
		));
	}
	
	public function preInsert($event){
		$this->date_added = date('Y-m-d');
	}
	
	public function preUpdate($event){
		$this->last_modified = date('Y-m-d');
	}
	
	public function setTableDefinition(){
		$this->setTableName('tax_rates');
		
		$this->hasColumn('tax_rates_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('tax_zone_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('tax_class_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('tax_priority', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '1',
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('tax_rate', 'decimal', 7, array(
		'type' => 'decimal',
		'length' => 7,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0.0000',
		'notnull' => true,
		'autoincrement' => false,
		'scale' => 4,
		));
		$this->hasColumn('tax_description', 'string', 255, array(
		'type' => 'string',
		'length' => 255,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('last_modified', 'timestamp', null, array(
		'type' => 'timestamp',
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('date_added', 'timestamp', null, array(
		'type' => 'timestamp',
		'primary' => false,
		'default' => '0000-00-00 00:00:00',
		'notnull' => true,
		'autoincrement' => false,
		));
	}
}