<?php
/**
 * Products
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ProductDesignerClipartImages extends Doctrine_Record {

	public function setUp(){
		$this->hasMany('ProductDesignerClipartImagesToCategories', array(
			'local'      => 'images_id',
			'foreign'    => 'images_id',
			'cascade'    => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('product_designer_clipart_images');

		$this->hasColumn('images_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));
		
		$this->hasColumn('image', 'string', 255, array(
			'type'          => 'string',
			'length'        => 255,
			'fixed'         => false,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));
	}
}