<?php
/**
 * ProductsToCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ProductDesignerClipartImagesToCategories extends Doctrine_Record {

	public function setUp(){
		$this->hasOne('ProductDesignerClipartCategories', array(
			'local' => 'categories_id',
			'foreign' => 'categories_id'
		));
		
		$this->hasOne('ProductDesignerClipartImages', array(
			'local' => 'images_id',
			'foreign' => 'images_id'
		));
	}
	
	public function setTableDefinition(){
		$this->setTableName('product_designer_clipart_images_to_categories');
		
		$this->hasColumn('images_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => false,
			'autoincrement' => false,
		));
		
		$this->hasColumn('categories_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => false,
			'autoincrement' => false,
		));
	}
}