<?php

/**
 * ProductsStreamProviders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ProductsStreamProviders extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();
		
		$this->hasMany('ProductsStreams', array(
			'local' => 'provider_id',
			'foreign' => 'provider_id'
		));
	}

	public function setUpParent(){
	}

	public function setTableDefinition(){
		$this->setTableName('products_stream_providers');
		
		$this->hasColumn('provider_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('provider_name', 'string', 255, array(
		'type' => 'string',
		'length' => 255,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('provider_module', 'string', 32, array(
		'type' => 'string',
		'length' => 32,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('provider_module_settings', 'string', 999, array(
		'type' => 'string',
		'length' => 999,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
	}
}