<?php

/**
 * Categories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BannerManagerGroups extends Doctrine_Record {
	
	public function setUp(){
		$this->hasMany('BannerManagerBannersToGroups', array(
			'local' => 'banner_group_id',
			'foreign' => 'banner_group_id',
			'cascade' => array('delete')
		));
	}
	
	public function setTableDefinition(){
		$this->setTableName('banner_manager_groups');
		
		$this->hasColumn('banner_group_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));

		$this->hasColumn('banner_group_name', 'string', 100, array(
			'type'          => 'string',
			'length'        => 100,
			'fixed'         => false,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_is_rotator', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_show_arrows', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_show_numbers', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_show_thumbnails', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_time', 'integer', 9, array(
			'type'          => 'integer',
			'length'        => 9,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '3000',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_effect', 'string', 40, array(
			'type'          => 'string',
			'length'        => 40,
			'fixed'         => false,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));
		$this->hasColumn('banner_group_effect_time', 'integer', 9, array(
			'type'          => 'integer',
			'length'        => 9,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '500',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_width', 'integer', 9, array(
			'type'          => 'integer',
			'length'        => 9,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '550',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_spw', 'integer', 3, array(
			'type'          => 'integer',
			'length'        => 3,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '7',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_sph', 'integer', 3, array(
			'type'          => 'integer',
			'length'        => 3,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '5',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_strips', 'integer', 3, array(
			'type'          => 'integer',
			'length'        => 3,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '10',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_height', 'integer', 9, array(
			'type'          => 'integer',
			'length'        => 9,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '220',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_thumbs_width', 'integer', 9, array(
			'type'          => 'integer',
			'length'        => 9,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '50',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_thumbs_height', 'integer', 9, array(
			'type'          => 'integer',
			'length'        => 9,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '50',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_show_description', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));
		$this->hasColumn('banner_group_auto_rotate', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_show_custom', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_show_thumbs_desc', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_use_autoresize', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_use_thumbs', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_auto_hide_title', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_auto_hide_numbers', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_auto_hide_thumbs', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_auto_hide_arrows', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_auto_hide_thumbs_desc', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_auto_hide_custom', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_hover_pause', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_description_opacity', 'decimal', 3, array(
			'type'          => 'decimal',
			'length'        => 3,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0.00',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('banner_group_is_expiring', 'integer', 1, array(
			'type'          => 'integer',
			'length'        => 1,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));
		//description position
	}
}