<?php

/**
 * ProductsToCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CategoriesPages extends Doctrine_Record {

	public function setUp(){
	}

	public function setTableDefinition(){
		$this->setTableName('categories_pages');
		
		$this->hasColumn('categories_pages_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => true,
		));
		
		$this->hasColumn('page_key', 'string', 100, array(
			'type' => 'string',
			'length' => 100,
			'fixed'         => false,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));

		$this->hasColumn('page_title', 'string', 100, array(
			'type' => 'string',
			'length' => 100,
			'fixed'         => false,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));

		$this->hasColumn('categories', 'string', null, array(
			'type' => 'string',
			'length' => null,
			'fixed'         => false,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));

	}
}