<?php

/**
 * CustomersStreamingViews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CustomersToOrders extends Doctrine_Record {
	
	public function setUp(){
		parent::setUp();
		//$this->setUpParent();

	}
	
	public function setUpParent(){
		/*$Customers = Doctrine::getTable('Customers')->getRecordInstance();
		
		$Customers->hasMany('CustomersToOrders', array(
			'local' => 'customers_id',
			'foreign' => 'customers_id',
			'cascade' => array('delete')
		));*/
		
	}

	public function setTableDefinition(){
		$this->setTableName('customers_to_orders');

		$this->hasColumn('customers_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('orders_id', 'integer', 4, array(
				'type' => 'integer',
				'length' => 4,
				'unsigned' => 0,
				'primary' => true,
				'notnull' => true,
				'autoincrement' => false,
		));
		$this->hasColumn('affiliate', 'string', null, array(
				'type' => 'string',
				'length' => null
		));
		$this->hasColumn('product', 'string', null, array(
				'type' => 'string',
				'length' => null
		));
		$this->hasColumn('cost', 'string', null, array(
				'type' => 'string',
				'length' => null
		));

	}
}