<?php

/**
 * ProductsToCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BannerManagerBannersToGroups extends Doctrine_Record {

	public function setUp(){
		$this->hasOne('BannerManagerBanners', array(
			'local' => 'banners_id',
			'foreign' => 'banners_id'
		));
		
		$this->hasOne('BannerManagerGroups', array(
			'local' => 'banner_group_id',
			'foreign' => 'banner_group_id'
		));
	}

	public function setTableDefinition(){
		$this->setTableName('banner_manager_banners_to_groups');
		
		$this->hasColumn('banners_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
		
		$this->hasColumn('banner_group_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
	}
}