<?php

/**
 * Blog Categories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BlogCategories extends Doctrine_Record {
	
	public function setUp(){ 
		$this->hasMany('BlogCategoriesDescription', array(
			'local'   => 'blog_categories_id',
			'foreign' => 'blog_categories_id',
			'cascade' => array('delete')
		));
	}
	
	public function setTableDefinition(){
		$this->setTableName('blog_categories');
		
		$this->hasColumn('blog_categories_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));

		
		$this->hasColumn('parent_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));
		
		$this->hasColumn('sort_order', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));
		$this->hasColumn('categories_image', 'string', 255, array(
				'type'          => 'string',
				'length'        => 255,
				'fixed'         => false,
				'primary'       => false,
				'default'       => '',
				'notnull'       => true,
				'autoincrement' => false
		));
		$this->hasColumn('extra_fields', 'string', null, array(
				'type'          => 'string',
				'length'        => null,
				'fixed'         => false,
				'primary'       => false,
				'default'       => '',
				'notnull'       => true,
				'autoincrement' => false
			));

		$this->hasColumn('extra_key', 'string', 200, array(
				'type'          => 'string',
				'length'        => 200,
				'fixed'         => false,
				'primary'       => false,
				'default'       => '',
				'notnull'       => true,
				'autoincrement' => false
			));

	}
}