<?php

/**
 * BlogCommentToPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BlogCommentToPost extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();
		
		$this->hasOne('BlogPosts', array(
			'local' => 'blog_post_id',
			'foreign' => 'post_id'
		));
		
		$this->hasOne('BlogComments', array(
			'local' => 'blog_comment_id',
			'foreign' => 'comment_id'
		));
	}

	public function setUpParent(){
		$Comments= Doctrine::getTable('BlogComments')->getRecordInstance();
		
		$Comments->hasMany('BlogCommentToPost', array(
			'local' => 'comment_id',
			'foreign' => 'blog_comment_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('blog_comment_to_post');
		
		$this->hasColumn('blog_comment_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
		
		$this->hasColumn('blog_post_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
	}
}