<?php

/**
 * ArticlesToTopics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ArticlesToTopics extends Doctrine_Record {
	
	public function setUp(){
		$this->hasOne('Articles', array(
			'local' => 'articles_id',
			'foreign' => 'articles_id'
		));
		
		$this->hasOne('Topics', array(
			'local' => 'topics_id',
			'foreign' => 'topics_id'
		));
	}
	
	public function setTableDefinition(){
		$this->setTableName('articles_to_topics');
		
		$this->hasColumn('articles_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('topics_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => false,
		));
	}
}