<?php

/**
 * Topics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Topics extends Doctrine_Record {
	
	public function setUp(){
		$this->hasMany('TopicsDescription', array(
			'local' => 'topics_id',
			'foreign' => 'topics_id',
			'cascade' => array('delete')
		));
		
		$this->hasMany('ArticlesToTopics', array(
			'local' => 'topics_id',
			'foreign' => 'topics_id',
			'cascade' => array('delete')
		));
	}
	
	public function preInsert($event){
		$this->date_added = date('y-m-d');
	}
	
	public function preSave($event){
		$this->last_modified = date('y-m-d');
	}
	
	public function setTableDefinition(){
		$this->setTableName('topics');
		
		$this->hasColumn('topics_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('topics_image', 'string', 64, array(
		'type' => 'string',
		'length' => 64,
		'fixed' => false,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('parent_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '0',
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('sort_order', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('date_added', 'timestamp', null, array(
		'type' => 'timestamp',
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('last_modified', 'timestamp', null, array(
		'type' => 'timestamp',
		'primary' => false,
		'notnull' => false,
		'autoincrement' => false,
		));
	}
}