<?php

/**
 * BlogPostToCategories
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BlogCategoriesToStores extends Doctrine_Record {

	public function setUp(){
		$Categories = Doctrine_Core::getTable('BlogCategories')->getRecordInstance();
		$Stores = Doctrine_Core::getTable('Stores')->getRecordInstance();

		$Categories->hasMany('BlogCategoriesToStores', array(
			'local'      => 'blog_categories_id',
			'foreign'    => 'blog_categories_id',
			'cascade'    => array('delete')
		));

		$Stores->hasMany('BlogCategoriesToStores', array(
			'local'      => 'stores_id',
			'foreign'    => 'stores_id',
			'cascade'    => array('delete')
		));
	}


	public function setTableDefinition(){
		$this->setTableName('blog_categories_to_stores');

		$this->hasColumn('blog_categories_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));

		$this->hasColumn('stores_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
	}
}