<?php

/**
 * Categories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class FeaturedManagerGroups extends Doctrine_Record {
	
	public function setUp(){
	}
	
	public function setTableDefinition(){
		$this->setTableName('featured_manager_groups');
		
		$this->hasColumn('featured_group_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));

		$this->hasColumn('featured_group_name', 'string', 100, array(
			'type'          => 'string',
			'length'        => 100,
			'fixed'         => false,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));

		$this->hasColumn('featured_group_number_of_products', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'primary'       => false,
			'notnull'       => true,
			'autoincrement' => false
		));

	}
}