<?php

/**
 * ProductsStream
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class PDFTemplateLayouts extends Doctrine_Record {
	
	public function setUp(){
		parent::setUp();

		$this->hasMany('PDFTemplatesInfoboxesToTemplates', array(
			'local' => 'layout_id',
			'foreign' => 'layout_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('template_layouts');
		
		$this->hasColumn('layout_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => true,
		));
		
		$this->hasColumn('layout_name', 'string', 128, array(
			'type' => 'string',
			'length' => 128,
			'fixed' => false,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));
		$this->hasColumn('template_name', 'string', 128, array(
			'type' => 'string',
			'length' => 128,
			'fixed' => false,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));
		$this->hasColumn('layout_content', 'clob', null, array(
			'type' => 'clob',
			'length' => null,
			'fixed' => false,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));
		$this->hasColumn('layout_content_source', 'clob', null, array(
			'type' => 'clob',
			'length' => null,
			'fixed' => false,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));
		$this->hasColumn('layout_css', 'clob', null, array(
			'type' => 'clob',
			'length' => null,
			'fixed' => false,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));

	}
}

