<?php

/**
 * TemplateManagerTemplatesStyles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $template_id
 * @property integer $definition_id
 * @property string $definition_key
 * @property time $definition_value
 * @property TemplateManagerTemplates $TemplateManagerTemplates
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PDFTemplateManagerTemplatesStyles extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('pdf_template_manager_templates_styles');
        $this->hasColumn('template_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('definition_id', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('definition_key', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('definition_value', 'string', null, array(
	        'type' => 'string',
        ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->setAttribute(Doctrine_Core::ATTR_COLL_KEY, 'definition_key');
        $this->hasOne('PDFTemplateManagerTemplates', array(
             'local' => 'template_id',
             'foreign' => 'template_id'));
    }
}