<?php

/**
 * CustomMenusItems
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CustomMenusItems extends Doctrine_Record {

	public function setUp(){
		$this->hasMany('CustomMenusItemsDescription', array(
			'local'   => 'menu_item_id',
			'foreign' => 'menu_item_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('custom_menus_items');

		$this->hasColumn('menu_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'autoincrement' => false
		));

		$this->hasColumn('menu_item_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));

		$this->hasColumn('parent_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));

		$this->hasColumn('menu_item_id_link', 'string', null, array(
			'type' => 'string',
			'length' => null,
			'fixed' => false,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));

		$this->hasColumn('menu_item_link', 'string', null, array(
			'type' => 'string',
			'length' => null,
			'fixed' => false,
			'primary' => false,
			'notnull' => true,
			'autoincrement' => false,
		));


	}

	public function getParentSubCategories($parentId, $languageId){
		$Qcategories = Doctrine_Query::create()
		->from('CustomMenusItems c')
		->leftJoin('c.CustomMenusItemsDescription cd')
		->where('c.parent_id = ?', $parentId)
		->andWhere('cd.language_id = ?', $languageId)
		->orderBy('c.sort_order, cd.menu_item_name')
		->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		return $Qcategories;
	}
}