<?php

/**
 * CustomMenusItemsDescription
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CustomMenusItemsDescription extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();

		$this->setAttribute(Doctrine::ATTR_COLL_KEY, 'language_id');

		$this->hasOne('CustomMenusItems', array(
			'local' => 'menu_item_id',
			'foreign' => 'menu_item_id'
		));
	}

	public function setUpParent(){
		$Categories = Doctrine::getTable('CustomMenusItems')->getRecordInstance();

		$Categories->hasMany('CustomMenusItemsDescription', array(
			'local' => 'menu_item_id',
			'foreign' => 'menu_item_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('custom_menu_items_description');

		$this->hasColumn('menu_item_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'autoincrement' => false
		));

		$this->hasColumn('language_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '1',
			'autoincrement' => false
		));

		$this->hasColumn('menu_item_name', 'string', 32, array(
			'type'          => 'string',
			'length'        => 32,
			'fixed'         => false,
			'primary'       => false,
			'default'       => '',
			'notnull'       => true,
			'autoincrement' => false
		));

	}

	public function getCategoryName($menuId, $languageId){
		$Query = Doctrine_Query::create()
		->select('menu_item_name')
		->from('CustomMenusItemsDescription')
		->where('menu_item_id = ?', $menuId)
		->andWhere('language_id = ?', $languageId)
		->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		return $Query[0]['menu_item_name'];
	}

	public function newLanguageProcess($fromLangId, $toLangId){
		$Qdescription = Doctrine_Query::create()
		->from('CustomMenusItemsDescription')
		->where('language_id = ?', (int) $fromLangId)
		->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		foreach($Qdescription as $Record){
			$toTranslate = array(
				'name'            => $Record['menu_item_name'],
			);

			EventManager::notify('CustomMenusItemsDescriptionLanguageProcessBeforeTranslate', $toTranslate);

			$translated = sysLanguage::translateText($toTranslate, (int) $toLangId, (int) $fromLangId);

			$newDesc = new CustomMenusItemsDescription();
			$newDesc->menu_item_id = $Record['menu_item_id'];
			$newDesc->language_id = (int) $toLangId;
			$newDesc->menu_item_name = $translated['name'];

			EventManager::notify('CustomMenusItemsDescriptionNewLanguageProcessBeforeSave', $newDesc);

			$newDesc->save();
		}
	}

	public function cleanLanguageProcess($existsId){
		Doctrine_Query::create()
		->delete('CustomMenusItemsDescription')
		->whereNotIn('language_id', $existsId)
		->execute();
	}

	public function deleteLanguageProcess($langId){
		Doctrine_Query::create()
		->delete('CustomMenusItemsDescription')
		->where('language_id = ?', (int) $langId)
		->execute();
	}
}
