<?php

/**
 * TemplateManagerLayoutsContainers
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $layout_id
 * @property integer $parent_id
 * @property integer $container_id
 * @property integer $sort_order
 * @property TemplateManagerLayouts $TemplateManagerLayouts
 * @property TemplateManagerLayoutsContainers $Parent
 * @property Doctrine_Collection $Columns
 * @property Doctrine_Collection $Children
 * @property Doctrine_Collection $Configuration
 * @property Doctrine_Collection $Styles
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TemplateManagerLayoutsContainers extends Doctrine_Record
{
	public function setTableDefinition()
	{
		$this->setTableName('template_manager_layouts_containers');
		$this->hasColumn('layout_id', 'integer', 11, array(
			'type' => 'integer',
			'length' => '11',
		));
		$this->hasColumn('parent_id', 'integer', 11, array(
			'type' => 'integer',
			'default' => 0,
			'notnull' => false,
			'length' => '11',
		));
		$this->hasColumn('container_id', 'integer', 11, array(
			'primary' => true,
			'type' => 'integer',
			'autoincrement' => true,
			'length' => '11',
		));
		$this->hasColumn('sort_order', 'integer', 3, array(
			'type' => 'integer',
			'length' => '3',
		));
		$this->hasColumn('is_anchor', 'integer', 1, array(
				'type' => 'integer',
				'length' => '1',
		));

		$this->hasColumn('anchor_id', 'integer', 11, array(
				'type' => 'integer',
				'length' => '11',
		));
	}

	public function setUp()
	{
		parent::setUp();
		$this->hasOne('TemplateManagerLayouts as Layout', array(
			'local' => 'layout_id',
			'foreign' => 'layout_id'));

		$this->hasOne('TemplateManagerLayoutsContainers as Parent', array(
			'local' => 'parent_id',
			'foreign' => 'container_id'));

		$this->hasMany('TemplateManagerLayoutsColumns as Columns', array(
			'local' => 'container_id',
			'foreign' => 'container_id',
			'orderBy' => 'sort_order',
			'cascade' => array('delete')));

		$this->hasMany('TemplateManagerLayoutsContainers as Children', array(
			'local' => 'container_id',
			'foreign' => 'parent_id',
			'orderBy' => 'sort_order',
			'cascade' => array('delete')));

		$this->hasMany('TemplateManagerLayoutsContainersConfiguration as Configuration', array(
			'local' => 'container_id',
			'foreign' => 'container_id',
			'cascade' => array('delete')));

		$this->hasMany('TemplateManagerLayoutsContainersStyles as Styles', array(
			'local' => 'container_id',
			'foreign' => 'container_id',
			'cascade' => array('delete')));
	}
}