<?php

/**
 * TemplateManagerTemplates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $template_id
 * @property Doctrine_Collection $Configuration
 * @property Doctrine_Collection $Styles
 * @property Doctrine_Collection $Layouts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TemplateManagerTemplates extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('template_manager_templates');
        $this->hasColumn('template_id', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => '11',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TemplateManagerTemplatesConfiguration as Configuration', array(
             'local' => 'template_id',
             'foreign' => 'template_id',
	        'cascade' => array('delete')));

        $this->hasMany('TemplateManagerTemplatesStyles as Styles', array(
             'local' => 'template_id',
             'foreign' => 'template_id',
	        'cascade' => array('delete')));

        $this->hasMany('TemplateManagerLayouts as Layouts', array(
             'local' => 'template_id',
             'foreign' => 'template_id',
	        'cascade' => array('delete')));
    }
}