<?php

/**
 * TemplateManagerLayoutsWidgets
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $column_id
 * @property integer $widget_id
 * @property string $identifier
 * @property integer $sort_order
 * @property TemplateManagerLayoutsColumns $TemplateManagerLayoutsColumns
 * @property Doctrine_Collection $Configuration
 * @property Doctrine_Collection $Styles
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TemplateManagerLayoutsWidgets extends Doctrine_Record
{
	public function setTableDefinition()
	{
		$this->setTableName('template_manager_layouts_widgets');
		$this->hasColumn('column_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
		));
		$this->hasColumn('widget_id', 'integer', 4, array(
			'primary' => true,
			'type' => 'integer',
			'autoincrement' => true,
			'length' => 4,
		));
		$this->hasColumn('identifier', 'string', 255, array(
			'type' => 'string',
			'length' => 255,
		));
		$this->hasColumn('sort_order', 'integer', 2, array(
			'type' => 'integer',
			'length' => 2,
		));
	}

	public function setUp()
	{
		parent::setUp();
		$this->hasOne('TemplatesInfoboxes', array(
			'local' => 'identifier',
			'foreign' => 'box_code'));

		$this->hasOne('TemplateManagerLayoutsColumns as Column', array(
			'local' => 'column_id',
			'foreign' => 'column_id'));

		$this->hasMany('TemplateManagerLayoutsWidgetsConfiguration as Configuration', array(
			'local' => 'widget_id',
			'foreign' => 'widget_id',
			'cascade' => array('delete')));

		$this->hasMany('TemplateManagerLayoutsWidgetsStyles as Styles', array(
			'local' => 'widget_id',
			'foreign' => 'widget_id',
			'cascade' => array('delete')));
	}
}