<?php

/**
 * CustomersStreamingViews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class RoyaltiesSystemViews extends Doctrine_Record {
	
	public function setUp(){
		$this->setUpParent();
		
		if (sysConfig::exists('EXTENSION_STREAMPRODUCTS_ENABLED')){
			$this->hasOne('ProductsStreams', array(
				'local' => 'streaming_id',
				'foreign' => 'stream_id'
			));
		}
		
		if (sysConfig::exists('EXTENSION_DOWNLOADPRODUCTS_ENABLED')){
			$this->hasOne('ProductsDownloads', array(
				'local' => 'download_id',
				'foreign' => 'download_id'
			));
		}
		
		$this->hasOne('Customers', array(
			'local' => 'customers_id',
			'foreign' => 'customers_id'
		));
	}
	
	public function setUpParent(){
		$Customers = Doctrine::getTable('Customers')->getRecordInstance();
		$Products = Doctrine::getTable('Products')->getRecordInstance();
		
		$Customers->hasMany('RoyaltiesSystemViews', array(
			'local' => 'customers_id',
			'foreign' => 'customers_id',
			'cascade' => array('delete')
		));

		$Products->hasMany('RoyaltiesSystemViews', array(
			'local' => 'products_id',
			'foreign' => 'products_id',
			'cascade' => array('delete')

		));
	}

	public function setTableDefinition(){
		$this->setTableName('royalties_system_views');

		$this->hasColumn('views_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => true,
		'notnull' => true,
		'autoincrement' => true,
		));
		$this->hasColumn('customers_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('products_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('streaming_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('download_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('date_added', 'timestamp', null, array(
		'type' => 'timestamp',
		'default' =>'0000-00-00 00:00:00',	
		'primary' => false,
		'notnull' => true,
		'autoincrement' => false,
		));
		$this->hasColumn('royalty', 'decimal', 15, array(
			'type' => 'decimal',
			'length' => 15,
			'unsigned' => 0,
			'primary' => false,
			'default' => '0.0000',
			'notnull' => true,
			'autoincrement' => false,
			'scale' => false,
		));
	}
}
