<?php

/**
 * ProductsToCategories
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CustomFieldsToCategories extends Doctrine_Record {

	public function setUp(){
		$this->setUpParent();

		$this->hasOne('ProductsCustomFields', array(
			'local' => 'field_id',
			'foreign' => 'field_id'
		));

		$this->hasOne('Categories', array(
			'local' => 'categories_id',
			'foreign' => 'categories_id'
		));
	}

	public function setUpParent(){
		$Categories = Doctrine::getTable('Categories')->getRecordInstance();

		$Categories->hasMany('CustomFieldsToCategories', array(
			'local' => 'categories_id',
			'foreign' => 'categories_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('custom_fields_to_categories');

		$this->hasColumn('field_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));

		$this->hasColumn('categories_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
	}
}