<?php

/**
 * OrdersStatusDescription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class PricePayPerRentalPerProductsDescription extends Doctrine_Record {

	public function setUp(){
		$this->setAttribute(Doctrine::ATTR_COLL_KEY, 'language_id');
	}
	
	public function setTableDefinition(){
		$this->setTableName('price_pay_per_rental_per_products_description');
		
		$this->hasColumn('price_per_rental_per_products_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'autoincrement' => false,
		));
		$this->hasColumn('language_id', 'integer', 4, array(
		'type' => 'integer',
		'length' => 4,
		'unsigned' => 0,
		'primary' => false,
		'default' => '1',
		'autoincrement' => false,
		));
		$this->hasColumn('price_per_rental_per_products_name', 'string', 232, array(
		'type' => 'string',
		'length' => 232,
		'fixed' => false,
		'primary' => false,
		'default' => '',
		'notnull' => true,
		'autoincrement' => false,
		));
	}
	
	public function newLanguageProcess($fromLangId, $toLangId){
		$Qdescription = Doctrine_Query::create()
		->from('PricePayPerRentalPerProductsDescription')
		->where('language_id = ?', (int) $fromLangId)
		->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		foreach($Qdescription as $Record){
			$toTranslate = array(
				'name' => $Record['price_per_rental_per_products_name']
			);
			
			EventManager::notify('PricePayPerRentalPerProductsDescriptionNewLanguageProcessBeforeTranslate', $toTranslate);
			
			$translated = sysLanguage::translateText($toTranslate, (int) $toLangId, (int) $fromLangId);
			
			$newDesc = new PricePayPerRentalPerProductsDescription();
			$newDesc->price_per_rental_per_products_id = $Record['price_per_rental_per_products_id'];
			$newDesc->language_id = (int) $toLangId;
			$newDesc->price_per_rental_per_products_name = $translated['name'];
			
			EventManager::notify('PricePayPerRentalPerProductsDescriptionNewLanguageProcessBeforeSave', $newDesc);
			
			$newDesc->save();
		}
	}

	public function deleteLanguageProcess($langId){
		Doctrine_Query::create()
		->delete('PricePayPerRentalPerProductsDescription')
		->where('language_id = ?', (int) $langId)
		->execute();
	}
}