<?php

/**
 * ImagesToCategories
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ImagesToCategories extends Doctrine_Record {

	public function setUp(){
		parent::setUp();
		$this->hasOne('PhotoGalleryCategories', array(
				'local' => 'categories_id',
				'foreign' => 'categories_id'
			));
	}

	public function setTableDefinition(){
		$this->setTableName('images_to_categories');

		$this->hasColumn('categories_id', 'integer', 4, array(
				'type'          => 'integer',
				'length'        => 4,
				'unsigned'      => 0,
				'primary'       => true,
				'autoincrement' => false
			));
		$this->hasColumn('file_name', 'string', 250, array(
				'type'          => 'string',
				'length'        => 250,
				'fixed'         => false,
				'primary'       => true,
				'notnull'       => false,
				'autoincrement' => false
		));

		$this->hasColumn('caption', 'string', 250, array(
				'type'          => 'string',
				'length'        => 250,
				'fixed'         => false,
				'primary'       => false,
				'notnull'       => false,
				'autoincrement' => false
		));
		$this->hasColumn('big_caption', 'string', null, array(
				'type'          => 'string',
				'length'        => null,
				'fixed'         => false,
				'primary'       => false,
				'notnull'       => false,
				'autoincrement' => false
		));
	}
}