<?php

/**
 * PhotoGalleryCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class PhotoGalleryCategories extends Doctrine_Record {
	
	public function setUp(){
		parent::setUp();
		$this->hasMany('PhotoGalleryCategoriesDescription', array(
			'local'   => 'categories_id',
			'foreign' => 'categories_id',
			'cascade' => array('delete')
		));
		$this->hasMany('ImagesToCategories', array(
				'local' => 'categories_id',
				'foreign' => 'categories_id',
				'cascade' => array('delete')
			));
	}

	public function preInsert($event){
		$this->date_added = date('Y-m-d');
	}

	public function preUpdate($event){
		$this->last_modified = date('Y-m-d');
	}
	
	public function setTableDefinition(){
		$this->setTableName('photo_gallery_categories');
		
		$this->hasColumn('categories_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true
		));

		$this->hasColumn('categories_image', 'string', 250, array(
				'type'          => 'string',
				'length'        => 250,
				'fixed'         => false,
				'primary'       => false,
				'notnull'       => false,
				'autoincrement' => false
		));
		
		$this->hasColumn('parent_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'default'       => '0',
			'notnull'       => true,
			'autoincrement' => false
		));
		
		$this->hasColumn('sort_order', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => false,
			'notnull'       => false,
			'autoincrement' => false
		));

		$this->hasColumn('date_added', 'timestamp', null, array(
				'type'          => 'timestamp',
				'primary'       => false,
				'notnull'       => false,
				'autoincrement' => false
			));

		$this->hasColumn('last_modified', 'timestamp', null, array(
				'type'          => 'timestamp',
				'primary'       => false,
				'notnull'       => false,
				'autoincrement' => false
			));

	}
}