<?php

/**
 * CustomersToCustomerGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CustomersWishlistProductAttributes extends Doctrine_Record {

	public function setUp(){
		parent::setUp();
		$this->setUpParent();
		
		$this->hasOne('CustomerWishlist', array(
			'local' => 'customers_wishlist_id',
			'foreign' => 'customer_wishlist_id'
		));

		$this->hasOne('ProductsAttributes', array(
			'local' => 'products_attributes_id',
			'foreign' => 'products_attributes_id'
		));

	}

	public function setUpParent(){
		$CustomersWishlist = Doctrine::getTable('CustomerWishlist')->getRecordInstance();

		$CustomersWishlist->hasMany('CustomersWishlistProductAttributes', array(
			'local' => 'customer_wishlist_id',
			'foreign' => 'customers_wishlist_id',
			'cascade' => array('delete')
		));

		$ProductsAttributes = Doctrine::getTable('ProductsAttributes')->getRecordInstance();

		$ProductsAttributes->hasMany('CustomersWishlistProductAttributes', array(
			'local' => 'products_attributes_id',
			'foreign' => 'products_attributes_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('customers_wishlist_product_attributes');
		
		$this->hasColumn('customers_wishlist_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
		
		$this->hasColumn('products_attributes_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => false,
		));
	}
}